apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    name: website
spec:
  initContainers:
  - name: git-clone
    image: debian:buster
    command: ["bash", "-c"]
    args:
    - |
      apt update && apt install -y git &&
      git clone https://github.com/mdn/beginner-html-site.git /workspace
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  containers:
  - name: webserver
    image: httpd
    volumeMounts:
    - name: workspace
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: workspace
    emptyDir: {}

